name: SCons Build with CodeQL

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install SCons
      run: |
        pip install scons

    - name: Set up CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: cpp
        # Customize this as needed
        database: my_database

    - name: Run SCons Build with CodeQL Wrapping
      run: |
        # Initialize the CodeQL database
        codeql database create my_database --language=cpp --source-root=. --command='scons'

    - name: Finalize CodeQL database
      uses: github/codeql-action/autobuild@v2

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
      with:
        category: 'security-extended'
        database: my_database

    - name: Upload CodeQL results
      uses: actions/upload-artifact@v3
      with:
        name: codeql-results
        path: results.sarif

